# Usa una imagen base con Python 3.12
FROM python:3.12-slim

# Crea un usuario no root por seguridad
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Dependencias de sistema (incluye libGL necesario para cv2 y Cairo para renderPM)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      libgl1 \
      libglib2.0-0 \
      curl \
      git \
      libcairo2 \
      libcairo2-dev \
      python3-cairo \
      libpango1.0-0 \
      libpangocairo-1.0-0 \
      pkg-config \
      libffi-dev \
      python3-cffi && \
    rm -rf /var/lib/apt/lists/*


# Crear usuario
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

# Establece el usuario por defecto
USER $USERNAME
